#
# Composes records from the (slightly edited) study plan text version
# loriacarlos@gmail.com
# input/study_plan.txt --> compose_output/composed_plan.txt
#
# Expected output record format generated by compose
# nn::code::description::credits[2345](::req)*::(bsc|dipl)::(level|_)::(cycle|_)
# req ~ EI(F|G)...O? | LIX...
#
# To run
# awk -f compose.awk input/study_plan.txt > compose_output/composed_plan.txt
#
#Ernesto Valerio Henández - 402070512
#José Fabio Alfaro Quesada - 207580494
#


BEGIN {
	ciclo="I";
	nivel="I";
	creditos=0;
	titulo="dipl";
	cont=1;
	nuevoCurso=0;
	req=0;
	reqOpt=0;
	credito=0;
	numOpt=1;
	nombre=0;
	cursosOpt=0;
	nuevoCursosOpt=0;
}

{
	if(cursosOpt==0){
		if(nuevoCurso==1 && credito==1){
			linea = linea $0 "::"
			credito=0;
		}
		if(nuevoCurso==1 && nombre==1){
			linea = linea $0 "::"
			credito=1;
			nombre=0;
		}
	}else
		if(cursosOpt==1 && nombre==1){
			linea = linea $0 "::" 3 "::";
			reqOpt=1;
			nombre=0;
		}
}

$0~/^EIF|^EIG|^MA|^LIX/{
	if(cursosOpt==0){
		if(nuevoCurso == 0){
			nuevoCurso=1;
			gsub(/ |-/, "", $0);
			linea = cont++ "::" $0 "::";
			nombre=1;
		}else{
			if(nuevoCurso==1){
				req = 1;
				gsub(/ |-/, "", $0);
				if(credito==1){
					linea = linea "::" 3 "::" $0 "::";
				}else
					if(credito==0){
					linea = linea $0 "::";
				}
			}
		}
	}else
		if(cursosOpt==1){
				if(reqOpt == 0){
				  gsub(/ |-/, "", $0);
					linea = cont++ "::" $0 "::";
					nombre=1;
				}else
					if(reqOpt==1){
						reqOpt++;
						if(length($1) == 3){
							nrc = armaNRC(nrc);
						}else{
							nrc = $1;
						}
						linea = linea nrc "::";
				}
		}

}


$1~/^Optativa/{
  optNombre = "Optativa" numRomano(numOpt);
	numOpt++;
	linea = cont++ "::" optNombre "::Optativa::" 3 "::Admission::" titulo "::" nivel "::" ciclo "\r";
	print linea;
}

$1~/^Ingreso/{
	linea = linea "Admission::" ;
}

$0~/^Estudios Generales/{
  nombre = $0;
	gsub(/ |-/, "", $0);
	linea = cont++ "::" $0 "::" nombre "::" 3 "::Admission::" titulo "::" nivel "::" ciclo "\r";
	print linea;
}


$2~/^Ciclo/{
	ciclo=$1;
}

$2~/^Nivel/{
	nivel=$1
}

$0~/^DIPLOMADO/{
  titulo="bsc";
}

$0~/^BACHILLERATO/{
  nivel="_";
	ciclo="_"
}

$1~/^$/ {
	if(nuevoCurso==1){
		nuevoCurso= 0;
		req=0;
		print linea= linea titulo "::" nivel "::" ciclo "\r";
	}
	if(reqOpt==1){
		reqOpt=0;
		print linea= linea "Admission::" titulo "::" nivel "::" ciclo "\r";
	}else
		if(reqOpt > 1){
			reqOpt=0;
			print linea= linea titulo "::" nivel "::" ciclo "\r";
	}
}

$1~/^OPTATIVOS/{
	cursosOpt=-1;
}

function numRomano (n){
	switch(n){
		case 1:
			return "I"
			break;
		case 2:
			return "II"
			break;
		case 3:
			return "III"
			break;
		case 4:
			return "IV"
			break;
		default:
			return "_"
			break;
	}
}

