# Generates prolog file from compose.awk output
# loriacarlos@gmail.com
# compose_output/composed_plan.txt --> prolog_output/study_plan.pl
# To run
# awk -f src/prolog.awk output/composed_plan.txt > prolog_output/study_plan.pl
#
#Ernesto Valerio Henández - 402070512
#José Fabio Alfaro Quesada - 207580494
#
BEGIN {
	FS = "::"
	print "%%%%% Study Plan %%%%%";
	print ":- discontiguous course/1.";
	print ":- discontiguous course/8.";
	print ":- discontiguous course_req/2.";
	course = "course";
	course_req = "course_req"
	Lheader = "% --- ";
	Rheader = " --- %";
	regular = "regular";
	optional = "optional";
}
# Expected input record format generated by compose
# nn::code::description::credits[2345](::req)*::(bsc|dipl)::(level|_)::(cycle|_)
# req ~ EI(F|G)...O? | LIX...

{


	if ($1!="" ){
		name = "\047" $2 "\047";
		desc = "\047" $3 "\047";
		cred = $4;
		ciclo = latino($NF);
		r = NF-1;
		n = NF-2;
		nivel = latino($r);
		titulo = $n;
		linea = Lheader name Rheader "\r";
		linea = linea course "(" name ").\r";
		if($NF != "_"){
			linea = linea course "(" name "," $1 "," regular "," titulo "," cred "," nivel "," ciclo "," desc ").\r";
		}else{
			linea = linea course "(" name "," $1 "," optional "," titulo "," cred "," nivel "," ciclo "," desc ").\r";
		}
		i = 5
		for(; i < n; i++){
			linea = linea course_req "(" name "," "\047" $i "\047" ").\r";
		}

		print linea;
	}
}

function latino(n){
	switch(n){
		case "I":
			return 1
			break;
		case "II":
			return 2
			break;
		case "III":
			return 3
			break;
		case "IV":
			return 4
			break;
		default:
			return "_"
			break;
	}
}

END{
}
